# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataSupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('pic_url', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('jianjie', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('content_url', models.CharField(max_length=256)),
                ('x', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u6570\u636e',
                'verbose_name_plural': '\u65b0\u95fb\u6570\u636e',
            },
        ),
    ]
