# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-24 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataSupport', '0002_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='x',
        ),
    ]
